set nocompatible
filetype off
set encoding=utf-8
syntax enable

set rtp+=~/.vim/bundle/vundle/
call vundle#begin()

" let Vundle manage Vundle
Plugin 'VundleVim/Vundle.vim'

" Bundles Here
Plugin 'altercation/vim-colors-solarized'
Plugin 'plasticboy/vim-markdown'
Plugin 'othree/html5.vim'
Plugin 'scrooloose/nerdtree'
Plugin 'kien/ctrlp.vim'
Plugin 'bling/vim-airline'
Plugin 'airblade/vim-gitgutter'
Plugin 'tpope/vim-fugitive'

call vundle#end()

colorscheme solarized

filetype plugin indent on
"
"" Brief help
" :PluginList       - lists configured plugins
" :PluginInstall    - installs plugins; append `!` to update or just :PluginUpdate
" :PluginSearch foo - searches for foo; append `!` to refresh local cache
" :PluginClean      - confirms removal of unused plugins; append `!` to auto-approve removal
"
" see :h vundle for more details or wiki for FAQ
" Put your non-Plugin stuff after this line


" Settings
set number
syntax enable
set background=dark
colorscheme solarized

" Yep, spaces
set smartindent
set tabstop=4
set shiftwidth=4
set expandtab

" No error noise on
" bad key-strokes, etc
set visualbell
set noerrorbells

" Change backup and swap dirs
" So these files don't appear in
" our project directories
set backupdir=~/.vim/backup//
set directory=~/.vim/swap//

" Set leader to comma
let mapleader = ","
let g:mapleader = ","

" Save via ',w'
nmap <leader>w :w!<cr>

" Run phpunit via ',t'
map <Leader>t :!phpunit %<cr>
nmap <Leader>tt :!phpunit<cr>

" Exit insert mode via 'jj'
imap jj <esc>

" Ctrl-n for NERDTree
" Ctrl-ww to switch between NERDTree and panes
map <C-n> :NERDTreeToggle<CR>

" CtrlP to open CtrlP
" Ctrl-T to open highlighted file in new tab

" User older-School (more font-friendly) directory
" arrows in directory listings
" Use this if set encoding utf-8 doesn't fix this issue:
" http://superuser.com/questions/401413/cant-open-folders-in-linux-nerdtree-vim
" https://github.com/scrooloose/nerdtree/issues/108
" let NERDTreeDirArrows=0

" Remove trailing spaces
" Within PHP files
autocmd BufWritePre *.php :%s/\s\+$//e

" Open composer.json file easily
" within a new tab via ',lc'
nmap <leader>lc :tabe composer.json<cr>

" Remove folding of markdown
" as per https://github.com/plasticboy/vim-markdown
let g:vim_markdown_folding_disabled=1

" Airline on all the time
set laststatus=2