#!/usr/bin/env bash
#
# This file acts as something of a front controller. It defines the
# environment for the framework and loads all the libraries before
# palming off the workload to the router (vpb.main).
# 

vpb() {
    # Detect if we are within the VM or not
    if [ -d /vagrant ] ; then
        VPB_IN_VM="yes"
    fi

    # Setup base path
    # TODO: This should be capable of being more dynamic
    if [ -d /vagrant ] ; then
        VPB_ROOT=/vagrant/.vpb
    else
        VPB_ROOT=./.vpb
    fi

    # Source the libs
    . ${VPB_ROOT}/lib/util.sh
    . ${VPB_ROOT}/lib/usage.sh
    . ${VPB_ROOT}/lib/lib.sh
    . ${VPB_ROOT}/lib/pkg.sh
    . ${VPB_ROOT}/lib/main.sh

    vpb.main $@
}

vpb $@
